---
title: "Data Modeling: Interpolation and Curve-Fitting"
engine: julia
---

This chapter deals with modeling discrete one-dimensional data with functions.

Tabular data has a discrete nature, therefore not allowing continuous
operations---such as continuous evaluations, derivation, integration, etc.---to
find maxima, minima, areas, and the like. Modeling tabular data allows one to
obtain a surrogate continuous function for the original tabular data.

One can identify two main approaches in constructing such a function: (i) one
that passes through all of the tabulated data points, i.e., an _interpolation_,
and (ii) one that captures the data behavior within a pre-defined funcion base,
i.e., _curve-fitting_.

## Interpolation

## Curve Fitting

### Motivation

```{julia}
#| echo: false
#| output: false
#| message: false

using Random
using Plots
gr()

function tmp_gen_lsq(; rnd = 0.25)
    __X = rand(15) * 6 .+ 1.0
    RND = rnd * rand(length(__X))
    CST = 10.0 + rand() * 5
    __Y = sin.(__X .- 1.0) + 0.5 * __X .+ CST + RND
    return (__X, __Y)
end

data = tmp_gen_lsq()

MODELS = Dict(
    :quadr => [
        x -> one(x),
        x -> x,
        x -> x^2,
    ],
    :cubic => [
        x -> one(x),
        x -> x,
        x -> x^2,
        x -> x^3,
    ],
)

function leastSq(the_x, the_y, MODEL)
    X = hcat([ F.(the_x) for F in MODEL ]...)
    y = copy(the_y)
    return a = X \ y
end

model(MOD, a, x) = sum(a .* [F.(x) for F in MOD])
```

Suppose one has tabular data from an experiment that relates a system performace
parameter, say, $y$, to input parameter $x$ values, as shown:

```{julia}
#| fig-width: 4
#| fig-height: 2
scatter(data...,
    xlabel="\$x\$",
    ylabel="\$y\$",
    label="data",
    legend=:bottomright,
    size=(480, 240),
)
```

The available data is limited, exists in irregular intervals, and show signs of
uncertainty. A designer of a new system or product of performance $y$ may need
(i) performace values for arbitrary $x$ values, (ii) information about local
maxima and minima for $y$, and (iii) the corresponding $x$ values, among other
info. Raw tabular data offer challenges to all these very applicable tasks.

### Data Modeling

Suppose one wants to _adjust_ a function to represent, as _adequately_ as
possible, the behavior (or _gist_) of the discrete data set, comprised of $n$
$(x, y)$ pairs, so that all needed continuos operations become possible once
such function is found.

In order to accomplish such a task, the function needs to be adjustable, i.e.,
to have as many degrees of freedom the analyst deems desirable or justifiable.
Therefore, the analyst (you) proposes (chooses) $m$ linearly independent
function _terms_, each one having its own adjustable _coefficients_, that is, a
function

$$
f(x) = \sum_{k = 1}^m a_k X_k(x)
$$ {#eq-fit-model}

which serves as a _model function_ for the data. The $X_k(x)$ functions compose
the function _base_ of the model, and the $a_k$ are the models _coefficients_.

The $m$ coefficients can then be adjusted to _some criteria_ as to render the
adjusted $f(x)$ an _estimator_ for the underlying $y(x)$ relationship expressed
by the discrete $n$ data points. The process involves determining (solving for)
the set of $m$ function coefficients $a_k$ that best fulfill the chosen
criteria.

### Least-Squares

One method of solving the data modeling problem is the _least-squares method_.
It consists in applying the crtiterion of _minimizing the sum of the squares of
the differences between the data point images, $y_i$, and the value of the model
function $f(x_i)$ over all $n$ data points_; that is to say:

$$
\mbox{minimize over $a_1 \ldots a_m$} \quad \sum_{i = 1}^n \left[y_i - f(x_i)\right]^2
$$ {#eq-least-sq}

The rationale is simple: by minimizing the sum of the deviations squared, not
only (potentially large) negative $y_i - f(x_i)$ differences won't cancel
(potentially large) positive ones, but also large differences get amplified,
thus inducing the function to stay close to the majority of the data points.

Least-squares as a method of maximum likelihood
[@william_h_press_numerical_2007{p. 776}]

One method of obtaining
